# Generated by Django 5.0.6 on 2024-06-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('america_car_renting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_renting',
            old_name='ownner_id',
            new_name='owner_id',
        ),
    ]
